MAT-5378
MeasureAuthoringTool/madie-editor pull request #140
Opened 2023-02-27 18:41 UTC by ethankaplan

## MADiE PR

Jira Ticket: [MAT-5378](https://jira.cms.gov/browse/MAT-5378)
(Optional) Related Tickets:

### Summary
Removed text for errors in CQL

### All Submissions
* [ ] This PR has the JIRA linked.
* [ ] Required tests are included
* [ ] No extemporaneous files are included (i.e Complied files or testing results)
* [ ] This PR is in to the **correct branch**.
* [ ] All Documentation as needed for this PR is Complete (or noted in a TODO or other Ticket)
* [ ] Any breaking changes or failing automation are noted by placing a comment on this PR.

### DevSecOps
If there is a question if this PR has a security or infrastructure impact, please contact the Security or DevOps engineer assigned to this project to discuss it further.

* [ ] This PR has NO significant security impact (i.e Changing auth methods, Adding a new user type, Adding a required but vulnerable package)
* [ ] All CDN/Web dependancies are hosted internally (i.e MADiE-Root Repo)

### Reviewers
By Approving this PR you are attesting to the following:

*  Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
*  The tests appropriately test the new code, including edge cases
*  If you have any concerns they are brought up either to the developer assigned, security engineer, or leads

2023-02-27 19:07 UTC, sb-prateekkeerthi requested changes

2023-02-27 19:07 UTC, sb-prateekkeerthi commented on src/AceEditor/madie-ace-editor.tsx
> +      return "";
Based on my understanding,  we don't want to show any message footer below the editor. 
1. If this the case we can remove the entire renderFooterMsg function 
2. or else if we decide we want to show the parsing message in footer we can remove the entire else if as we don't need that condition now(as if we are not showing any issues found info)

2023-02-27 19:17 UTC, ethankaplan commented on src/AceEditor/madie-ace-editor.tsx
> +      return "";
1. I'll follow up with Nilki, I can see it being either possibility now that you mention it.
2. The empty return clears out the "Parsing..." message; if it's just the else, it will say success when there is an error

2023-03-02 15:09 UTC, sb-prateekkeerthi approved these changes

2023-03-02 15:14 UTC, merged